language: c
env:
  global:
    - RACKET_DIR=~/racket
    - Z3_DIR=~/z3
    - RACKET_VERSION="6.10"
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - git clone https://github.com/Z3Prover/z3.git "${Z3_DIR}"
  - (cd "${Z3_DIR}" && python scripts/mk_make.py)
  - (cd "${Z3_DIR}"/build && make)
  - export PATH="${RACKET_DIR}/bin:${Z3_DIR}/build:${PATH}"
script:
  - make test
